[package]
name = "vowpalwabbit-sys"
version = "8.6.1-beta"
authors = ["Jack Gerrits <jack@jackgerrits.com>"]
edition = "2018"
links = "libvw_c_wrapper"

[build-dependencies]
pkg-config = "0.3.14"
bindgen = "0.49.2"