/* automatically generated by rust-bindgen 0.59.2 */

pub const VW_STATUS_SUCCESS: ::std::os::raw::c_int = 0;
pub const VW_STATUS_FAIL: ::std::os::raw::c_int = 1;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct VWWorkspace {
    _unused: [u8; 0],
}
extern "C" {
    pub fn VWInitializeWorkspace(
        symbols: *const *const ::std::os::raw::c_char,
        count: ::std::os::raw::c_int,
        output_handle: *mut *mut VWWorkspace,
        error_message: *mut *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn VWFreeWorkspace(
        workspace_handle: *mut VWWorkspace,
        error_message: *mut *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn VWFreeErrorMessage(
        error_message: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn VWRunDriver(
        workspace_handle: *mut VWWorkspace,
        error_message: *mut *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
