[package]
name = "par-dsjson-unbounded"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vowpalwabbit = { path = "../vowpalwabbit" }
crossbeam-channel = "0.5.6"
rayon = "1.5.3"
itertools = "0.10.4"
