name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          [
            { os: ubuntu-latest, preset: vcpkg },
            { os: macos-latest, preset: vcpkg },
            { os: windows-latest, preset: vcpkg-windows },
          ]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - if: ${{ startsWith(matrix.config.os, 'windows') }}
        shell: cmd
        run: echo set(VCPKG_BUILD_TYPE release) >> binding/vcpkg/triplets/x64-windows-static.cmake
      - if: ${{ startsWith(matrix.config.os, 'ubuntu') }}
        run: echo "set(VCPKG_BUILD_TYPE release)" >> binding/vcpkg/triplets/x64-linux.cmake
      - if: ${{ startsWith(matrix.config.os, 'macos') }}
        run: echo "set(VCPKG_BUILD_TYPE release)" >> binding/vcpkg/triplets/x64-osx.cmake
      - name: Setup MSVC Developer Command Prompt
        if: ${{ startsWith(matrix.config.os, 'windows') }}
        uses: ilammy/msvc-dev-cmd@v1
      - uses: lukka/get-cmake@latest
      - uses: lukka/run-vcpkg@main
        with:
          vcpkgDirectory: "${{ github.workspace }}/binding/vcpkg"
          vcpkgJsonGlob: "${{ github.workspace }}/binding/vcpkg.json"
      - uses: lukka/run-cmake@v10
        with:
          cmakeListsTxtPath: "${{ github.workspace }}/binding/CMakeLists.txt"
          configurePreset: "${{ matrix.config.preset }}"
          buildPreset: "${{ matrix.config.preset }}"
      - if: ${{ startsWith(matrix.config.os, 'windows') == false }}
        working-directory: binding
        run: sudo cmake --install build --strip
      - if: ${{ startsWith(matrix.config.os, 'windows') }}
        working-directory: binding
        run: cmake --install build --strip
      - if: ${{ startsWith(matrix.config.os, 'windows') }}
        shell: powershell
        run: |
          "C:/Program Files (x86)/vowpalwabbit-rs-bindings/bin/" >> $env:GITHUB_PATH
          "VW_RS_BINDING_HOME=C:/Program Files (x86)/vowpalwabbit-rs-bindings" >> $env:GITHUB_ENV
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: -vv
        env:
          # Required to make it work in some Linux situations
          LD_LIBRARY_PATH: /lib:/usr/lib:/usr/local/lib
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: -vv
        env:
          # Required to make it work in some Linux situations
          LD_LIBRARY_PATH: /lib:/usr/lib:/usr/local/lib
